### ISSUE TITLE
add LICENSE please

### ISSUE THREAD

**Issue by teaalltr** [wongfei/pdb-ripper#1]

**Comment by wongfei** [comment]
this code is experimental and has copyrighted deps
check the header of https://github.com/wongfei/pdb-ripper/blob/master/dia2dump.cpp
not sure it fits some license

**Comment by teaalltr** [comment]
You could remove the deps from within the repo itself and import the DIA sdk header instead
The interface should remain be the same

**Comment by wongfei** [comment]
i don't recommend using something from this repo directly, the code quality is very low and was made just to test some ideas, but in case you want, the x_ prefixed files are unlicensed

**Comment by teaalltr** [comment]
I'm studying the code, expecially the part retrieving and printing the class hierarchy. My goal would be to recover complete class declarations (including specifiers such as Private, Protected and Friend) in the right order (using line number info too) so to recover the original headers almost completely. 
I may fix something upstream to you. I use it as a reference for the moment. If you're interested, we could work together on it

Thanks for sharing your work btw
