### ISSUE TITLE
CoCreateInstance failed - HRESULT = 80040154

### ISSUE THREAD

**Issue by ghost** [wongfei/pdb-ripper#2]
When I tried to dump all info of a specific pdb file, it gave me the error with HRESULT value 80040154, which said Class not registered. Below is where the error occurred.
`hr = CoCreateInstance(__uuidof(DiaSource),
                        NULL,
                        CLSCTX_INPROC_SERVER,
                        __uuidof(IDiaDataSource),
                        (void **) ppSource);`
So what's wrong?

**Comment by wongfei** [comment]
path and dll name depends on vs version: 

c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\

regsvr32.exe msdia140.dll

**Comment by ghost** [comment]
Got it. Thx

**Comment by tnqiang** [comment]
Refs:https://learn.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/dia2dump-sample?view=vs-2022
